name: Deploy with SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            REPO_NAME=${{ github.event.repository.name }}
            APP_DIR="/home/${{ secrets.DEPLOY_USER }}/$REPO_NAME"

            mkdir -p "$APP_DIR"
            cd "$APP_DIR"

            if [ -d ".git" ]; then
              echo "üåÄ Pulling latest code..."
              git pull origin main
            else
              echo "‚¨áÔ∏è Cloning repo..."
              git clone git@github.com:${{ github.repository }} "$APP_DIR"
              cd "$APP_DIR"
            fi

            echo "üîß Installing dependencies..."
            sudo systemctl restart $REPO_NAME.service
            echo "üì¶ Building the project..."

            echo "üîÑ Check service..."
            # curl -I localhost:8989
            echo "üöÄ Deployment complete!"
